### ISSUE TITLE
Allow using Sphinx 4

### ISSUE THREAD

**Issue by vberlier** [executablebooks/MyST-NB#338]
# Summary

Right now `sphinx>=2,<4` in [setup.cfg](https://github.com/executablebooks/MyST-NB/blob/e39132e4f1c58352a9f6d3004c7336dbbeca4e8a/setup.cfg#L51) makes it impossible to use `myst-nb` with Sphinx 4. `myst-parser` upgraded to Sphinx 4 recently https://github.com/executablebooks/MyST-Parser/pull/390.

# Tasks to complete

- [ ] Try removing the Sphinx to `<5` here
      https://github.com/executablebooks/MyST-NB/blob/master/setup.cfg#L51
      and bump myst-parser to the latest version here:
      https://github.com/executablebooks/MyST-NB/blob/master/setup.cfg#L47
- [ ] Run tests and make changes needed to make them pass
- [ ] Merge in, then we should cut a new release

**Comment by choldgraf** [comment]
Indeed - the next step to get this is to update the MyST Parser dependency, which will bring support for Sphinx 4 when that happens (https://github.com/executablebooks/MyST-Parser/blob/master/CHANGELOG.md#0150---2021-06-13). There might need to be some other changes too though.

**Comment by vberlier** [comment]
Just checking in. Is there anything we can do to help move this forward?

**Comment by MegChai** [comment]
Any progress?  👀

**Comment by chrisjsewell** [comment]
Well myst-parser is updated, so this should now work in principle

**Comment by MegChai** [comment]
> Well myst-parser is updated, so this should now work in principle

Cool. I will have a try and give some feedback asap.

**Comment by chrisjsewell** [comment]
Note we would want `myst-parser~=0.15.1`

**Comment by chrisjsewell** [comment]
A notable potential change, would be to set `dmath_double_inline=True` as standard, to mirror the current Jupyter Notebook render behaviour

**Comment by MegChai** [comment]
```shell
INFO: pip is looking at multiple versions of sphinx-togglebutton to determine which version is compatible with other requirements. This could take a while.
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
```

When I add `mystnb` and `myst-parser` into my `requirements.txt` file, it will take a long time to determine other packages' version. It that means I have to use specific version for those package?

```
sphinx>=4.0
sphinx-intl
sphinxcontrib-mermaid>=0.7
sphinx-copybutton
sphinx-tabs
sphinx-togglebutton
sphinx-panels
jieba
ipython
recommonmark
nbsphinx
beautifulsoup4
```

**Comment by MegChai** [comment]
https://github.com/executablebooks/MyST-NB/blob/c98d4322503e58f947eeea478e005785b178b7f0/setup.cfg#L51 it was required that `sphinx>=2,<4`

```
The conflict is caused by:
    The user requested sphinx>=4.0
    sphinx-copybutton 0.4.0 depends on sphinx>=1.8
    sphinx-tabs 3.1.0 depends on sphinx<5 and >=2
    sphinx-togglebutton 0.2.3 depends on sphinx
    sphinx-panels 0.6.0 depends on sphinx<5 and >=2
    myst-nb 0.12.3 depends on sphinx<4 and >=2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by chrisjsewell** [comment]
> it was required that sphinx>=2,<4

oh no what I mean is that it should work with the change to myst-nb, to `sphinx>=2,<5`

**Comment by chrisjsewell** [comment]
but yeh it won't work yet for the current published version

**Comment by choldgraf** [comment]
any chance that @mmcky or @AakashGfude would be able to tackle this one? If we can get MyST-NB to Sphinx 4, then we can also get sphinx-book-theme to Sphinx 4, and then Jupyter Book to Sphinx 4!

**Comment by mmcky** [comment]
@choldgraf yup -- I added this to the `Next Up` on the Activity Board. I am going to take a look at this soon.
